version: "3"

services:

  mysql-fradoos:
    image: mariadb:10.0.34
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./build/data/fradoos:/var/lib/mysql
    ports:
      - 3306:3306