CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE company (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
ALTER TABLE user ADD company_id INT DEFAULT NULL;
ALTER TABLE user ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE NO ACTION;
CREATE INDEX IDX_8D93D649979B1AD6 ON user (company_id);
CREATE TABLE working_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE user_working_group (user_id INT NOT NULL, working_group_id INT NOT NULL, INDEX IDX_DE788825A76ED395 (user_id), INDEX IDX_DE7888258856E875 (working_group_id), PRIMARY KEY(user_id, working_group_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
ALTER TABLE user_working_group ADD CONSTRAINT FK_DE788825A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE user_working_group ADD CONSTRAINT FK_DE7888258856E875 FOREIGN KEY (working_group_id) REFERENCES working_group (id);
